# Generated by Django 4.2.2 on 2023-08-22 14:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('image', models.BinaryField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('caption', models.TextField()),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
