# Generated by Django 4.2.2 on 2023-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_follower_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
